# Generated by Django 5.2.13 on 2026-04-25 12:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='总分')),
                ('recommendation', models.CharField(choices=[('strong_recommend', '强烈推荐'), ('recommend', '建议采用'), ('revise', '建议修改后再用')], max_length=30, verbose_name='结论建议')),
                ('overall_comment', models.TextField(verbose_name='总体评价')),
                ('comparative_comment', models.TextField(blank=True, verbose_name='双教案比较')),
                ('strengths', models.TextField(blank=True, verbose_name='优势亮点')),
                ('improvement_suggestions', models.TextField(blank=True, verbose_name='改进建议')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lesson_plans.lessonplanbatch', verbose_name='所属批次')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '教案评价',
                'verbose_name_plural': '教案评价',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanReviewDimensionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dimension_key', models.CharField(max_length=64, verbose_name='维度标识')),
                ('dimension_name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='权重')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='分数')),
                ('comment', models.TextField(blank=True, verbose_name='维度说明')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_scores', to='reviews.lessonplanreview', verbose_name='所属评价')),
            ],
            options={
                'verbose_name': '维度评分',
                'verbose_name_plural': '维度评分',
                'ordering': ['dimension_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='lessonplanreview',
            constraint=models.UniqueConstraint(fields=('batch', 'reviewer'), name='unique_review_per_batch_per_user'),
        ),
        migrations.AddConstraint(
            model_name='lessonplanreviewdimensionscore',
            constraint=models.UniqueConstraint(fields=('review', 'dimension_key'), name='unique_dimension_score_per_review'),
        ),
    ]
