# Generated by Django 5.2.13 on 2026-04-26 07:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_existing_scores(apps, schema_editor):
    Review = apps.get_model("reviews", "LessonPlanReview")
    DimensionScore = apps.get_model("reviews", "LessonPlanReviewDimensionScore")

    for item in DimensionScore.objects.all():
        item.score_a = item.score
        item.score_b = item.score
        item.save(update_fields=["score_a", "score_b"])

    for review in Review.objects.all():
        review.total_score_a = review.total_score
        review.total_score_b = review.total_score
        review.save(update_fields=["total_score_a", "total_score_b"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplanreview',
            name='total_score_a',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='教案A总分'),
        ),
        migrations.AddField(
            model_name='lessonplanreview',
            name='total_score_b',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='教案B总分'),
        ),
        migrations.AddField(
            model_name='lessonplanreviewdimensionscore',
            name='score_a',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='教案A分数'),
        ),
        migrations.AddField(
            model_name='lessonplanreviewdimensionscore',
            name='score_b',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='教案B分数'),
        ),
        migrations.RunPython(copy_existing_scores, noop_reverse),
        migrations.AlterField(
            model_name='lessonplanreviewdimensionscore',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='综合分数'),
        ),
    ]
