# Generated by Django 5.2.13 on 2026-04-25 12:28

import apps.lesson_plans.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='批次标题')),
                ('subject', models.CharField(max_length=100, verbose_name='学科')),
                ('grade_level', models.CharField(max_length=100, verbose_name='适用学段/年级')),
                ('academic_year', models.CharField(blank=True, max_length=50, verbose_name='学年')),
                ('teaching_theme', models.CharField(blank=True, max_length=200, verbose_name='教学主题')),
                ('cover_summary', models.TextField(blank=True, verbose_name='批次说明')),
                ('review_deadline', models.DateField(blank=True, null=True, verbose_name='评价截止日期')),
                ('status', models.CharField(choices=[('processing', '解析中'), ('ready', '可评价'), ('failed', '解析失败'), ('archived', '已归档')], default='processing', max_length=20, verbose_name='状态')),
                ('ready_document_count', models.PositiveSmallIntegerField(default=0, verbose_name='已完成解析文档数')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='评价数')),
                ('average_total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='平均总分')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '教案批次',
                'verbose_name_plural': '教案批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_number', models.PositiveSmallIntegerField(verbose_name='组内顺序')),
                ('title', models.CharField(max_length=200, verbose_name='教案标题')),
                ('original_file', models.FileField(upload_to=apps.lesson_plans.models.lesson_plan_upload_path, verbose_name='原始文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_extension', models.CharField(max_length=20, verbose_name='文件扩展名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('parse_status', models.CharField(choices=[('pending', '待解析'), ('processing', '解析中'), ('ready', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='解析状态')),
                ('extracted_text', models.TextField(blank=True, verbose_name='抽取文本')),
                ('rendered_html', models.TextField(blank=True, verbose_name='渲染 HTML')),
                ('parse_error', models.TextField(blank=True, verbose_name='解析错误')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='页数')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lesson_plans.lessonplanbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '教案文档',
                'verbose_name_plural': '教案文档',
                'ordering': ['slot_number', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'slot_number'), name='unique_document_slot_per_batch')],
            },
        ),
    ]
