# Generated by Django 5.2.13 on 2026-04-25 14:16

import apps.lesson_plans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplandocument',
            name='display_mode',
            field=models.CharField(choices=[('html', 'HTML 渲染'), ('pdf', '版式预览')], default='html', max_length=20, verbose_name='展示方式'),
        ),
        migrations.AddField(
            model_name='lessonplandocument',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.lesson_plans.models.lesson_plan_preview_path, verbose_name='预览文件'),
        ),
    ]
